// Generated by tools/vibe_icons.py -- do not edit.
// App logos for the Vibe Voice Device; see assets/icons/vibe-voice/README.md.
#pragma once

#include "lvgl.h"

#define VV_ICON_COUNT 4

// Index = Supported App (TARGET_STATE app): 0 Orca, 1 WeChat, 2 ChatGPT, 3 WeCom.
extern const lv_image_dsc_t *const vv_icons_96[VV_ICON_COUNT];
extern const lv_image_dsc_t *const vv_icons_20[VV_ICON_COUNT];
